Add MainButton
gsarthakdev/dormit-rusher-app pull request #1
Opened 2022-08-20 07:12 UTC by sepehrheravi

2022-08-20 18:43 UTC, gsarthakdev commented on App.js
> +    //Testing Button
Remove line of code.

2022-08-20 18:44 UTC, gsarthakdev commented on App.js
> +    <View style={styles.container}>
Remove line of code.

2022-08-20 18:44 UTC, gsarthakdev commented on App.js
> +      <MainButton>Sign In</MainButton>
Remove line of code.

2022-08-20 18:44 UTC, gsarthakdev commented on App.js
> +    </View>
Remove line of code.

2022-08-20 18:45 UTC, gsarthakdev commented on App.js
> +    //Testing Button
Please remove the following code: 
```   
    //Testing Button
    <View style={styles.container}>
      <MainButton>Sign In</MainButton>
    </View>

2022-08-20 18:47 UTC, gsarthakdev commented on components/MainButton.js
> +        style={({ pressed }) => [{ opacity: pressed ? 0.75 : 1 }]}
Change to: 

`style={({pressed}) => pressed && {opacity: 0.75}}`

2022-08-20 18:50 UTC, gsarthakdev commented on components/MainButton.js
> +  container: { flex: 1, justifyContent: "center", alignItems: "center" },
`container` style is not needed for components, such as buttons. 

Please remove `container` style from the StyleSheet.

2022-08-20 18:50 UTC, gsarthakdev commented on components/MainButton.js
> +    <View style={styles.container}>
When creating custom buttons with Pressable, a wrapper `<View> </View>` is not needed, please remove it.

2022-08-20 18:51 UTC, gsarthakdev commented on components/MainButton.js
> +    color: "#FFFFFF",
Please change to `color: "white"`

2022-08-20 18:51 UTC, gsarthakdev commented on components/MainButton.js
> +  text: {
Change style name to `label`.

2022-08-20 18:52 UTC, gsarthakdev commented on components/MainButton.js
> +export default MainButton;
Move this `export default MainButton;` statement to Line 19, right before you declare `const styles =`

2022-08-20 19:01 UTC, gsarthakdev commented on constants/styles.js
> +    purpleBackground: "#7141FA",
Change `purpleBackground` to `primaryPurple`

2022-08-20 19:03 UTC, gsarthakdev requested changes
Please review the comments on all three files and make the changes requested.

2022-08-21 02:07 UTC, sepehrheravi reviewed
The changes were made per your request.

2022-08-21 21:02 UTC, gsarthakdev approved these changes
Approved `Add MainButton`

2022-08-21 21:03 UTC, merged