UI order setting screens
gsarthakdev/dormit-rusher-app pull request #11
Opened 2022-09-15 05:09 UTC by sepehrheravi

2022-09-26 23:21 UTC, gsarthakdev commented on components/BrandHeader.js
> +    display: 'felx',
Typo

2022-09-26 23:21 UTC, gsarthakdev commented on constants/styles.js
> +    deviderColor: "#EEEEEE",
Typo

2022-09-26 23:23 UTC, gsarthakdev requested changes
Please see attached comments.

2022-09-29 03:16 UTC, sepehrheravi reviewed
All the requested changes were made

2022-09-29 03:17 UTC, gsarthakdev approved these changes

2022-10-01 20:42 UTC, merged