UI brand header
gsarthakdev/dormit-rusher-app pull request #2
Opened 2022-08-21 04:19 UTC by sepehrheravi

2022-08-21 21:18 UTC, gsarthakdev commented on components/BrandHeader.js
> +import { useFonts, Poppins_700Bold } from "@expo-google-fonts/poppins";
Please download the font files for `poppins` from google fonts, add it to assets/fonts folder, and use the downloaded fonts, not through online fonts.

2022-08-21 21:20 UTC, gsarthakdev requested changes
Please check the comments and make the necessary changes.

2022-08-21 22:01 UTC, sepehrheravi commented
Changes were applied

2022-08-21 22:21 UTC, gsarthakdev requested changes
Please check the comments.

2022-08-21 22:21 UTC, gsarthakdev commented on components/BrandHeader.js
> +    "poppins-bold": require("../assets/Poppins-Bold.ttf"),
As I mentioned in the comments before, please add the font file to assets/fonts folder. This means that you will have to create a `fonts` folder inside of the `assets` folder

2022-08-21 22:38 UTC, gsarthakdev requested changes
Please view the comments and make the necessary changes.

2022-08-21 22:38 UTC, gsarthakdev commented on components/BrandHeader.js
> -  const [fontLoaded] = useFonts({
Please load the fonts in `App.js` so that they can be loaded when the app loads and can be used throughout the whole app in any screen file or component.

2022-08-22 00:17 UTC, gsarthakdev approved these changes
Approved.

2022-08-22 00:17 UTC, merged